FROM node:18

WORKDIR /opt/app

RUN mkdir -p /opt/app &&\
    addgroup app &&\
    adduser app --ingroup app --disabled-password &&\
    chown -R app /opt/app

COPY packages/frontend/ ./

COPY node_modules/ ./node_modules

RUN yarn build

USER app

EXPOSE 80

CMD [ "npm", "start" ]